INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('PETER','RODRIGUEZ');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('PETER','HILL');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('PETER','CAMPBELL');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('NOAH','RODRIGUEZ');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('NOAH','DAVIS');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('ASHER','RODRIGUEZ');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('ASHER','PEREZ');
INSERT INTO PERSON (`FIRST_NAME`,`LAST_NAME`) VALUES ('REAGAN','CAMPBELL');